/*
 * PreviewSetupForm.java
 * Created on 08 December 2006, 17:03
 * GUI for audio and video encoding using mencoder and mplayer
 * Copyright (C) Damien Farrell
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 */

package jmencode;
import javax.swing.*;

public class PreviewSetupForm extends javax.swing.JFrame {
    MainGUI maingui;
    /** Creates new form PreviewSetupForm */
    public PreviewSetupForm(MainGUI parent) {
        initComponents();
        maingui = parent;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        prevframestartField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prevsetupOKButton = new javax.swing.JButton();
        prevsetupCancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        previncrField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setTitle("Preview Setup");
        jLabel1.setText("Start Preview at");

        prevframestartField.setText(Float.toString(Settings.prevstarttime));

        jLabel2.setText("secs");

        prevsetupOKButton.setText("OK");
        prevsetupOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevsetupOKButtonActionPerformed(evt);
            }
        });

        prevsetupCancelButton.setText("Cancel");
        prevsetupCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevsetupCancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Preview Increment:");

        previncrField.setText(Integer.toString(Settings.stepsize));

        jLabel4.setText("secs");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(jLabel1))
                        .add(13, 13, 13))
                    .add(layout.createSequentialGroup()
                        .add(prevsetupOKButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(prevsetupCancelButton)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, prevframestartField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, previncrField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(previncrField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(prevframestartField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(prevsetupCancelButton)
                    .add(prevsetupOKButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevsetupCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevsetupCancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_prevsetupCancelButtonActionPerformed

    private void prevsetupOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevsetupOKButtonActionPerformed
        
        Settings.stepsize = Integer.parseInt(previncrField.getText());
        Settings.prevstarttime = Float.parseFloat(prevframestartField.getText());
        this.setVisible(false);
        maingui.previewVideo("input", "still");
    }//GEN-LAST:event_prevsetupOKButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PreviewSetupForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField prevframestartField;
    private javax.swing.JTextField previncrField;
    private javax.swing.JButton prevsetupCancelButton;
    private javax.swing.JButton prevsetupOKButton;
    // End of variables declaration//GEN-END:variables
    
}
