/*
 * PreviewSetupForm.java
 * Created on 08 December 2006, 17:03
 * GUI for audio and video encoding using mencoder and mplayer
 * Copyright (C) Damien Farrell
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
 */

package jmencode;
import javax.swing.*;

public class RescaleOptionsForm extends javax.swing.JFrame {
    MainGUI maingui;
    /** Creates new form PreviewSetupForm */
    public RescaleOptionsForm(MainGUI parent) {
        initComponents();
        maingui = parent;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        prevframestartField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rescaleOptionsOKButton = new javax.swing.JButton();
        prevsetupCancelButton = new javax.swing.JButton();
        useMod16Box = new javax.swing.JCheckBox();
        if (Settings.usemod16 == true){
            useMod16Box.setSelected(true);
        } else{
            useMod16Box.setSelected(false);
        }
        useAnamorphicBox = new javax.swing.JCheckBox();

        setTitle("Rescaling Options");
        setResizable(false);
        jLabel1.setText("Show Preview at");

        prevframestartField.setText(Float.toString(Settings.prevstarttime));

        jLabel2.setText("secs");

        rescaleOptionsOKButton.setText("OK");
        rescaleOptionsOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rescaleOptionsOKButtonActionPerformed(evt);
            }
        });

        prevsetupCancelButton.setText("Cancel");
        prevsetupCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevsetupCancelButtonActionPerformed(evt);
            }
        });

        useMod16Box.setText("Use Mod16 Scaling");
        useMod16Box.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useMod16Box.setMargin(new java.awt.Insets(0, 0, 0, 0));
        useMod16Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useMod16BoxActionPerformed(evt);
            }
        });

        useAnamorphicBox.setText("Keep Anamorphic");
        useAnamorphicBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        useAnamorphicBox.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rescaleOptionsOKButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(prevsetupCancelButton)
                        .add(22, 22, 22))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .add(useAnamorphicBox)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel1)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(prevframestartField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabel2))
                            .add(useMod16Box))))
                .add(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(useMod16Box)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(useAnamorphicBox)
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(prevframestartField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rescaleOptionsOKButton)
                    .add(prevsetupCancelButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void useMod16BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useMod16BoxActionPerformed
        if (useMod16Box.isSelected() == true){
            Settings.usemod16 = true;
        } else{
            Settings.usemod16 = false;
        }
        int oldval = Settings.scalew ;
        Settings.setScaleValues(oldval);    //will set values according to mod 16 if set true

    }//GEN-LAST:event_useMod16BoxActionPerformed
    
    private void prevsetupCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevsetupCancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_prevsetupCancelButtonActionPerformed
    
    private void rescaleOptionsOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rescaleOptionsOKButtonActionPerformed
        
        Settings.prevstarttime = Float.parseFloat(prevframestartField.getText());
        this.setVisible(false);
        maingui.previewVideo("input", "still");
    }//GEN-LAST:event_rescaleOptionsOKButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new PreviewSetupForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField prevframestartField;
    private javax.swing.JButton prevsetupCancelButton;
    private javax.swing.JButton rescaleOptionsOKButton;
    private javax.swing.JCheckBox useAnamorphicBox;
    private javax.swing.JCheckBox useMod16Box;
    // End of variables declaration//GEN-END:variables
    
}
